### ISSUE TITLE
Installation failed on Windows

### ISSUE THREAD

**Issue by mhlozek** [wingsuit-designsystem/wingsuit#115]
I tried to install wingsuite on Windows 10, but get this error:

```
√ cwebp pre-build test passed successfully
  √ gifsicle pre-build test passed successfully
  √ mozjpeg pre-build test passed successfully
  √ optipng pre-build test passed successfully
  √ pngquant pre-build test passed successfully

 ws init - the simplest way to install Wingsuit.

Cloning Wingsuit repo ...
Checking out latest tag...
Running Wingsuit dependency installation...
Running Wingsuit setup...
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn mv ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:464:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn mv',
  path: 'mv',
  spawnargs: [ 'D:\\Www\\wscheckout/starter-kits/tailwind', 'D:\\Www\\wingsuit' ]
}
```

Is there any solution for this problem please?

**Comment by christianwiedemann** [comment]
@mhlozek Yes I tested only on Mac and on Linux. But actually, it should be an easy fix. Will let you know

**Comment by christianwiedemann** [comment]
@mhlozek I fixed it in beta37. Would be great if you can test it. 

```
npx @wingsuit-designsystem/cli init
cd wingsuit
yarn install 
yarn dev:storybook
```

Thanks Christian

**Comment by mhlozek** [comment]
Just test it and it is up and running. Thank you very much for great work!

And only one notice: there is a typo on Quickstart guide page (https://wingsuit-designsystem.github.io/guides/quick-start-guide/):

`npx @wingsuit-designsystem/cli init -k bootrap`

should be

`npx @wingsuit-designsystem/cli init -k bootstrap`

**Comment by christianwiedemann** [comment]
@mhlozek Thanks for reporting and thanks for the typo. Let me know if you have any questions.
